"""
Django settings for chou project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-35^f)h3whuarfygi%w^vs4l==(k*rcwss)re13!+zv$6d$zej-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['chou-xixo.onrender.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'orders',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Read the DATABASE_URL from environment for security, fall back to the provided Neon URL
DATABASE_URL = os.environ.get(
    'DATABASE_URL',
    "postgresql://neondb_owner:npg_VPhx2CyQk8Dp@ep-spring-wind-adg3i4kw-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
)

# Second database for orders
ORDERS_DATABASE_URL = os.environ.get(
    'ORDERS_DATABASE_URL',
    "postgresql://neondb_owner:npg_N2qUxwFYr4CQ@ep-misty-shadow-a4h4siyf-pooler.us-east-1.aws.neon.tech/orders_db?sslmode=require&channel_binding=require"
)

# Parse the default DATABASE_URL
_parsed_db = urlparse(DATABASE_URL)
_query = parse_qs(_parsed_db.query)

# Parse the orders DATABASE_URL
_parsed_orders_db = urlparse(ORDERS_DATABASE_URL)
_orders_query = parse_qs(_parsed_orders_db.query)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _parsed_db.path.lstrip('/'),
        'USER': _parsed_db.username,
        'PASSWORD': _parsed_db.password,
        'HOST': _parsed_db.hostname,
        'PORT': str(_parsed_db.port) if _parsed_db.port else '5432',
        # Convert query params like sslmode and channel_binding into OPTIONS
        'OPTIONS': {k: v[0] for k, v in _query.items()},
    },
    'orders_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _parsed_orders_db.path.lstrip('/'),
        'USER': _parsed_orders_db.username,
        'PASSWORD': _parsed_orders_db.password,
        'HOST': _parsed_orders_db.hostname,
        'PORT': str(_parsed_orders_db.port) if _parsed_orders_db.port else '5432',
        # Convert query params like sslmode and channel_binding into OPTIONS
        'OPTIONS': {k: v[0] for k, v in _orders_query.items()},
    }
}


# Database Router for multiple databases
DATABASE_ROUTERS = ['chou.db_router.OrdersRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# Allow all Vercel deployment URLs (production and previews) plus localhost
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://chou-front.*\.vercel\.app$",  # Matches all chou-front Vercel deployments
    r"^https://brikoula.*\.vercel\.app$",     # Matches all brikoula Vercel deployments
]

CORS_ALLOWED_ORIGINS = [
    'https://brikoula.vercel.app',   # Production domain
    'http://localhost:3000',          # For local development
]

# Allow credentials (cookies, authorization headers) in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Allow all headers and methods
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Telegram Bot Configuration for Order Notifications
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '')
